language: c
before_install:
    - sudo apt-get install gcc-4.6-arm-linux-gnueabi
    - sudo ln -s /usr/bin/arm-linux-gnueabi-gcc-4.6 /usr/bin/arm-linux-gnueabi-gcc
compiler:
    - gcc
script: make mx2_defconfig; make ARCH=arm CROSS_COMPILE=arm-linux-gnueabi-
